# Use docker-based build environment (instead of openvz)
sudo: false
language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8

cache:
  directories:
    - '$HOME/.ivy2/cache'

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/4f1883358fd00b380a4e'
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
