#!/bin/bash

[ -z "PS1" ] && trap "error_exit" 1 2 3 15 ERR 

SBT_VERSION=0.13.5

SBT_DOWNLOAD="http://dl.bintray.com/sbt/native-packages/sbt/${SBT_VERSION}/sbt-${SBT_VERSION}.tgz"

function error_exit 
{
	echo "An error has happened, shutting down" 
	[ -f ./stop-all.sh ] && ./stop-all.sh
	exit 1
}

SBT_DIR=~/.sbt-jars
SBT_ARTIFACT=sbt-${SBT_VERSION}-launch.jar
SBT_TMP=/tmp/sbt-${SBT_VERSION}.tgz
SBT_FILE=${SBT_DIR}/${SBT_ARTIFACT}

if [ ! -f ${SBT_FILE} ]
then
	mkdir -p ${SBT_DIR}
	echo "Downloading ${SBT_DOWNLOAD}"
	curl -o ${SBT_TMP} -L "${SBT_DOWNLOAD}"
	rm -rf /tmp/sbt
	tar zxvf ${SBT_TMP} -C /tmp
	cp /tmp/sbt/bin/sbt-launch.jar ${SBT_FILE}
fi
