version: 2
jobs:
  build:
    working_directory: ~/emailaddress
    docker:
      - image: codestar/circleci-scala-sbt-git:scala-2.12.3-sbt-0.13.16
    steps:
      - checkout

      - restore_cache:
          keys:
            - emailaddress-{{ checksum "project/build.sbt" }}-{{ checksum "build.sbt" }}
            - emailaddress

      - run:
          # TODO: For some reason circleci gets stuck in the shell if we don't add exit to sbt
          command:
            sbt compile test:compile exit

      - save_cache:
          key: emailaddress-{{ checksum "project/build.sbt" }}-{{ checksum "build.sbt" }}
          paths:
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
            - ~/.sbt
            - ~/.iv2/cache
            - ~/.m2
      - save_cache:
          # Changing this to a different key is the only way to remove old dependencies from the cache and/or generate a more up-to-date cache
          key: emailaddress
          paths:
            - ~/.sbt
            - ~/.iv2/cache
            - ~/.m2

      - run:
          command:
            sbt test exit

      - store_test_results:
          path: target/test-reports